language: java

addons:
    apt:
        packages:
            - oracle-java8-installer

git:
    depth: 1

branches:
    only:
        - Dec2016Lite-Java

before_cache:
    - rm -f  $HOME/monetdb-java-lite/.gradle/caches/modules-2/modules-2.lock
    - rm -rf $HOME/monetdb-java-lite/.gradle/caches/*/plugin-resolution/

cache:
    directories:
        - $HOME/monetdb-java-lite/.gradle/caches/
        - $HOME/monetdb-java-lite/.gradle/wrapper/

before_install:
    - sudo apt-get install -qq autoconf automake libtool gettext gcc-mingw-w64

before_script:
    - wget http://services.gradle.org/distributions/gradle-3.4.1-bin.zip
    - unzip gradle-3.4.1-bin.zip
    - export GRADLE_HOME=$PWD/gradle-3.4.1
    - export PATH=$GRADLE_HOME/bin:$PATH

script:
    - jdk_switcher use oraclejdk8
    - ./.travisscript.sh

