language: java

addons:
    apt:
        packages:
            - oracle-java8-installer

jdk:
    - oraclejdk8

git:
    depth: 3

branches:
    only:
        - Dec2016Lite-Java

before_cache:
    - rm -f  $HOME/monetdb-java-lite/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/monetdb-java-lite/.gradle/caches/*/plugin-resolution/

cache:
    directories:
        - $HOME/monetdb-java-lite/.gradle/caches/
        - $HOME/monetdb-java-lite/.gradle/wrapper/

matrix:
    include:
        - os: linux
        - os: osx

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq autoconf automake libtool gettext ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install autoconf automake libtool gettext ; fi

before_script:
    - wget http://services.gradle.org/distributions/gradle-3.4.1-bin.zip
    - unzip gradle-3.4.1-bin.zip
    - export GRADLE_HOME=$PWD/gradle-3.4.1
    - export PATH=$GRADLE_HOME/bin:$PATH

script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./linux.sh ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./macos.sh ; fi

